create table public.fees (
  id bigint generated by default as identity not null,
  student_id uuid not null,
  fee_structure_id uuid null,
  total_fee numeric(10, 2) not null default 0,
  paid_fee numeric(10, 2) not null default 0,
  payment_status text not null default 'pending'::text,
  fee_cycle text not null,
  cycle_start_date date not null,
  cycle_end_date date not null,
  is_current_cycle boolean null default false,
  sub_fees jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  institute_id uuid null,
  session_id uuid null,
  constraint fees_pkey primary key (id),
  constraint fees_session_id_fkey foreign KEY (session_id) references sessions (id),
  constraint fees_student_id_fkey foreign KEY (student_id) references students (id) on update CASCADE on delete CASCADE,
  constraint fees_institute_id_fkey foreign KEY (institute_id) references institutes (id),
  constraint fees_fee_structure_id_fkey foreign KEY (fee_structure_id) references fee_structures (id) on update CASCADE on delete CASCADE,
  constraint fees_payment_status_check check (
    (
      payment_status = any (
        array['pending'::text, 'partial'::text, 'paid'::text]
      )
    )
  ),
  constraint fees_fee_cycle_check check (
    (
      fee_cycle = any (
        array[
          'monthly'::text,
          'quarterly'::text,
          'semester'::text,
          'yearly'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_fees_student on public.fees using btree (student_id) TABLESPACE pg_default;

create index IF not exists idx_fees_fee_structure on public.fees using btree (fee_structure_id) TABLESPACE pg_default;

create index IF not exists idx_fees_cycle_dates on public.fees using btree (cycle_start_date, cycle_end_date) TABLESPACE pg_default;